// Code generated by qtc from "auth.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package auth

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func (data *Forbidden) StreamTitle(qw422016 *qt422016.Writer) {
	qw422016.N().S(`Ошибка 403`)
}

func (data *Forbidden) WriteTitle(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	data.StreamTitle(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (data *Forbidden) Title() string {
	qb422016 := qt422016.AcquireByteBuffer()
	data.WriteTitle(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (data *Forbidden) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<p>Доступ запрещён
`)
}

func (data *Forbidden) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	data.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (data *Forbidden) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	data.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (data *Restricted) StreamTitle(qw422016 *qt422016.Writer) {
	qw422016.N().S(`Запретная страница`)
}

func (data *Restricted) WriteTitle(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	data.StreamTitle(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (data *Restricted) Title() string {
	qb422016 := qt422016.AcquireByteBuffer()
	data.WriteTitle(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (data *Restricted) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<p>Посторонним вход воспрещён
`)
}

func (data *Restricted) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	data.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (data *Restricted) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	data.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
