// Code generated by qtc from "page.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	"sumbur/views/static"
)

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type HTML interface {
	Title() string
	StreamTitle(qw422016 *qt422016.Writer)
	WriteTitle(qq422016 qtio422016.Writer)
	Body() string
	StreamBody(qw422016 *qt422016.Writer)
	WriteBody(qq422016 qtio422016.Writer)
}

type BasePage struct{}

func (page *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
}

func (page *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	page.StreamTitle(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (page *BasePage) Title() string {
	qb422016 := qt422016.AcquireByteBuffer()
	page.WriteTitle(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (page *BasePage) StreamBody(qw422016 *qt422016.Writer) {
}

func (page *BasePage) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	page.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (page *BasePage) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	page.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func StreamPage(qw422016 *qt422016.Writer, module int, page HTML) {
	qw422016.N().S(`<!DOCTYPE html>

<html lang="ru">


<head>

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>`)
	page.StreamTitle(qw422016)
	qw422016.N().S(` — sumbur.info</title>

<link rel="stylesheet" href="/static/modern-normalize.min.css">
<link rel="stylesheet" href="`)
	qw422016.E().S(static.Stamp("sumbur.css"))
	qw422016.N().S(`">

</head>


<body>


<div id="page">


<header class="dark">

<div>

<ul id="menu">
`)
	for mi, item := range Menu {
		qw422016.N().S(`<li><a href="/`)
		qw422016.E().Z(item.link)
		qw422016.N().S(`"`)
		if mi == module {
			qw422016.N().S(` class="active"`)
		}
		qw422016.N().S(`>`)
		qw422016.E().Z(item.label)
		qw422016.N().S(`</a></li>
`)
	}
	qw422016.N().S(`</ul>

</div>

<div>
…
</div>

</header>


<main>
`)
	page.StreamBody(qw422016)
	qw422016.N().S(`</main>


<footer class="dark">

<div>
© 2019–2022 Николай Новиков
</div>

<div>
<a href="mailto:sumbur@sumbur.info">sumbur@sumbur.info</a>
</div>

</footer>


</div>


<script defer src="`)
	qw422016.E().S(static.Stamp("sumbur.js"))
	qw422016.N().S(`"></script>

</body>


</html>
`)
}

func WritePage(qq422016 qtio422016.Writer, module int, page HTML) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamPage(qw422016, module, page)
	qt422016.ReleaseWriter(qw422016)
}

func Page(module int, page HTML) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WritePage(qb422016, module, page)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
